# Generated by Django 4.0.5 on 2022-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_category_options_category_slug_fooditem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Slug will be generated automatically from the name of the category', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(help_text='Slug will be generated automatically from the name of the food item', max_length=100, unique=True),
        ),
    ]
