# Generated by Django 4.0.5 on 2022-07-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='description',
        ),
    ]
