# Generated by Django 4.0.5 on 2022-07-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
