# Generated by Django 4.0.5 on 2022-07-03 10:35

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_order_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=management.models.category_image_path),
        ),
    ]
