# Generated by Django 4.0.5 on 2022-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_category_created_at_fooditem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
