# Generated by Django 4.0.5 on 2022-07-03 10:51

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_category_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=management.models.category_image_path),
        ),
    ]
