# Generated by Django 4.0.5 on 2022-07-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='quantity_available',
            field=models.IntegerField(default=5),
        ),
    ]
