# Generated by Django 4.0.5 on 2022-07-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_fooditem_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
    ]
