# Generated by Django 4.0.5 on 2022-07-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_quantityunit_ingredient_fooditem_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
