# Generated by Django 4.0.5 on 2022-07-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_rename_ingredient_fooditem_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantityunit',
            options={'verbose_name_plural': 'Ingredients Quantity Unit'},
        ),
        migrations.CreateModel(
            name='FoodItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='management.fooditemingredient'),
        ),
    ]
