# Generated by Django 4.0.5 on 2022-07-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_quantityunit_options_fooditemingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditemingredient',
            options={'verbose_name_plural': 'Food items ingredients'},
        ),
    ]
