# Generated by Django 4.0.5 on 2022-07-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_fooditemingredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': 'Ingredients Available'},
        ),
        migrations.AddField(
            model_name='fooditemingredient',
            name='unit',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='management.quantityunit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditemingredient',
            name='ingredient',
            field=models.ForeignKey(help_text="Ingredient required for this food item. (if ingredient you are looking for is not available you can add it by clicking on '+' icon.", on_delete=django.db.models.deletion.CASCADE, to='management.ingredient'),
        ),
        migrations.AlterField(
            model_name='fooditemingredient',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity required of the ingredient for this food item'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Name of the ingredient you want to add to inventory', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_available',
            field=models.IntegerField(default=0, help_text='Quantity of the ingredient available in the inventory'),
        ),
    ]
