# Generated by Django 4.0.5 on 2022-07-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
