# Generated by Django 4.0.5 on 2022-07-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_ingredient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditemingredient',
            name='quantity',
            field=models.FloatField(help_text='Quantity required of the ingredient for this food item'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_available',
            field=models.FloatField(default=0, help_text='Quantity of the ingredient available in the inventory'),
        ),
    ]
