# Generated by Django 4.0.5 on 2022-07-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_alter_fooditemingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='limit',
            field=models.FloatField(default=0, help_text='Please specify the limit in the same unit as the quantity available. This limit is to alert the admin if the ingredient is running low.'),
        ),
    ]
